# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 14:45
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='author name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='author/avatars/')),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
